# Generated by Django 4.2.2 on 2023-06-11 17:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 6, 11, 20, 44, 52, 562024)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 20, 44, 52, 562024), verbose_name=datetime.datetime(2023, 6, 11, 20, 44, 52, 562024)),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='awesome title', max_length=255),
        ),
    ]
